package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.model.CreateProjectRequest;
import com.probestack.forgestudio.design.model.Project;
import com.probestack.forgestudio.design.model.UUID;
import com.probestack.forgestudio.design.model.UpdateProjectRequest;
import com.probestack.forgestudio.design.repository.ProjectReqRepository;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for CreateProjectRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class ProjectsService {
    private final ProjectReqRepository createProjectRequestRepository;

    public ProjectsService(ProjectReqRepository createProjectRequestRepository) {
        this.createProjectRequestRepository = createProjectRequestRepository;
    }

    public ResponseEntity<Project> createProject(CreateProjectRequest createProjectRequest) {
        // Save the entity to database
        CreateProjectRequest savedCreateProjectRequest = createProjectRequestRepository.save(createProjectRequest);
        // Map entity to response DTO
        Project response = mapToProject(savedCreateProjectRequest);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    public ResponseEntity<Project> getProject(UUID projectId) {
        // Retrieve entity by ID from database
        Optional<CreateProjectRequest> entity = createProjectRequestRepository.findById(projectId);
        // Map entity to response DTO
        return entity.map(this::mapToProject).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());
    }

    public ResponseEntity<List<Project>> listProjects() {
        // Retrieve all entities from database
        List<CreateProjectRequest> entities = createProjectRequestRepository.findAll();
        // Map entities to response DTOs
        List<Project> responses = entities.stream().map(this::mapToProject).collect(Collectors.toList());
        return ResponseEntity.ok(responses);
    }

    public ResponseEntity<Project> updateProject(UUID projectId,
            UpdateProjectRequest updateProjectRequest) {
        // TODO: Implement custom business logic
        // Available repository methods:
        //   - save(entity) - Create or update
        //   - findById(id) - Find by ID
        //   - findAll() - Get all entities
        //   - existsById(id) - Check if exists
        //   - deleteById(id) - Delete by ID
        //   - count() - Count all entities
        return null;
    }

    /**
     * Maps CreateProjectRequest entity to Project response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private Project mapToProject(CreateProjectRequest entity) {
        // Create new response object
        Project response = new Project();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
