package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.model.AddProjectMemberRequest;
import com.probestack.forgestudio.design.model.ProjectMember;
import com.probestack.forgestudio.design.model.UUID;
import com.probestack.forgestudio.design.model.Void;
import com.probestack.forgestudio.design.repository.ProjectMemberReqRepository;
import java.util.List;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for AddProjectMemberRequest operations.
 *
 * <p>This service uses MongoDB repository for data persistence.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class ProjectMembersService {
    private final ProjectMemberReqRepository addProjectMemberRequestRepository;

    public ProjectMembersService(
            ProjectMemberReqRepository addProjectMemberRequestRepository) {
        this.addProjectMemberRequestRepository = addProjectMemberRequestRepository;
    }

    public ResponseEntity<List<ProjectMember>> projectsProjectIdMembersGet(UUID projectId) {
        // Retrieve all entities from database
        List<AddProjectMemberRequest> entities = addProjectMemberRequestRepository.findAll();
        // Map entities to response DTOs
        List<ProjectMember> responses = entities.stream().map(this::mapToProjectMember).collect(Collectors.toList());
        return ResponseEntity.ok(responses);
    }

    public ResponseEntity<Void> projectsProjectIdMembersPost(UUID projectId,
            AddProjectMemberRequest addProjectMemberRequest) {
        // Save the entity to database
        AddProjectMemberRequest savedAddProjectMemberRequest = addProjectMemberRequestRepository.save(addProjectMemberRequest);
        return ResponseEntity.status(HttpStatus.CREATED).body(savedAddProjectMemberRequest);
    }

    /**
     * Maps AddProjectMemberRequest entity to ProjectMember response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private ProjectMember mapToProjectMember(AddProjectMemberRequest entity) {
        // Create new response object
        ProjectMember response = new ProjectMember();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
