package com.probestack.forgestudio.design.repository;

import com.probestack.forgestudio.design.model.CreateProjectRequest;
import java.lang.Long;
import org.springframework.data.mongodb.repository.MongoRepository;

/**
 * MongoDB repository for CreateProjectRequest entities.
 *
 * <p>This repository extends MongoRepository which provides standard CRUD operations:</p>
 * <ul>
 * <li>save(entity) - Create or update an entity</li>
 * <li>findById(id) - Find entity by ID</li>
 * <li>findAll() - Retrieve all entities</li>
 * <li>existsById(id) - Check if entity exists</li>
 * <li>deleteById(id) - Delete entity by ID</li>
 * <li>count() - Count all entities</li>
 * </ul>
 *
 * @author Generated by ProbeStack CodeGen
 */
public interface CreateProjectRequestRepository extends MongoRepository<CreateProjectRequest, Long> {
}
